services:
  - type: web
    name: ncaa-soccer-dashboard
    env: python
    runtime: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
